/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgranhotel.Vistas;

import elgranhotel.Data.HuespedData;
import elgranhotel.Entidades.Huesped;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leo Huari
 */
public class CrearReservas extends javax.swing.JPanel {
    private DefaultTableModel modeloHuesped = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    private DefaultTableModel modeloHabitacion = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    private HuespedData huespedData = new HuespedData();
    private ArrayList<Huesped> listaHuespedes = huespedData.ListarHuesped();
    private Huesped huesped = new Huesped();
    /**
     * Creates new form CrearReservas
     */
    public CrearReservas() {
        initComponents();
        armarTablaHuesped();
        cargarTablaHuespedes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpContenedor1 = new javax.swing.JPanel();
        jcbFiltroHuesped = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtfBuscador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHuespedes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jpContenedor2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jdcFechaIn = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jdcFechaOut = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jtfCantPers = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jcbTipoHab = new javax.swing.JComboBox<>();
        jtfCantPersRestantes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtHabitaciones = new javax.swing.JTable();
        jbCompletarReserva = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setPreferredSize(new java.awt.Dimension(980, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbFiltroHuesped.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbFiltroHuesped.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "DNI", "Nombre" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Buscar huesped por: ");

        jtfBuscador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfBuscador.setText("Buscar ...");
        jtfBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfBuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscadorFocusLost(evt);
            }
        });
        jtfBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscadorActionPerformed(evt);
            }
        });
        jtfBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscadorKeyReleased(evt);
            }
        });

        jtHuespedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtHuespedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHuespedesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtHuespedes);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("jButton1");

        javax.swing.GroupLayout jpContenedor1Layout = new javax.swing.GroupLayout(jpContenedor1);
        jpContenedor1.setLayout(jpContenedor1Layout);
        jpContenedor1Layout.setHorizontalGroup(
            jpContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedor1Layout.createSequentialGroup()
                .addGroup(jpContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContenedor1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcbFiltroHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpContenedor1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jtfBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpContenedor1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jpContenedor1Layout.setVerticalGroup(
            jpContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedor1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbFiltroHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        add(jpContenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 940, 380));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Fecha de Ingreso: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de Salida: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad de personas: ");

        jtfCantPers.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpContenedor2Layout = new javax.swing.GroupLayout(jpContenedor2);
        jpContenedor2.setLayout(jpContenedor2Layout);
        jpContenedor2Layout.setHorizontalGroup(
            jpContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedor2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jpContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContenedor2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfCantPers, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpContenedor2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jpContenedor2Layout.setVerticalGroup(
            jpContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedor2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jdcFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(jpContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCantPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(jpContenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 910, 130));

        jcbTipoHab.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbTipoHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "DS", "DQ", "TS", "TSQ", "CS", "C2SQ", "SL" }));

        jtfCantPersRestantes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfCantPersRestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCantPersRestantesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad de peronas restantes:");

        jtHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtHabitaciones);

        jbCompletarReserva.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbCompletarReserva.setText("Completar Reserva");

        jbCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tipo Habitación");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCantPersRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jbCancelar)
                        .addGap(104, 104, 104)
                        .addComponent(jbCompletarReserva))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCantPersRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCompletarReserva)
                    .addComponent(jbCancelar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 890, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBuscadorActionPerformed

    private void jtfCantPersRestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCantPersRestantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCantPersRestantesActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtfBuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscadorKeyReleased
        borrarFilasHuespedes();
        String variable = null;
        
        for(Huesped huesped : listaHuespedes){
            switch(jcbFiltroHuesped.getSelectedIndex()){
                case 0:
                    variable = huesped.getIdHuesped() + "";
                    break;
                case 1:
                    variable = huesped.getDni() + "";
                    break;
                case 2:
                    variable = huesped.getNombre().toLowerCase();
                    break;
            }
            
            if(variable.startsWith(jtfBuscador.getText().toLowerCase())){
                modeloHuesped.addRow(new Object[]{
                    huesped.getIdHuesped(),
                    huesped.getNombre(),
                    huesped.getDni(),
                    huesped.getCorreo(),
                    huesped.getCelular(),
                    huesped.getDomicilio(),
                    huesped.isEstado()
                });
            }else if(jtfBuscador.getText().isEmpty()){
                cargarTablaHuespedes();
            }
        }
    }//GEN-LAST:event_jtfBuscadorKeyReleased

    private void jtfBuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscadorFocusGained
        jtfBuscador.setText("");
    }//GEN-LAST:event_jtfBuscadorFocusGained

    private void jtfBuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscadorFocusLost
        if (jtfBuscador.getText().isEmpty()) 
            jtfBuscador.setText("Buscar ...");
    }//GEN-LAST:event_jtfBuscadorFocusLost

    private void jtHuespedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHuespedesMouseClicked
        int i =jtHuespedes.getSelectedRow();
        boolean estado = (boolean)jtHuespedes.getValueAt(i, 6);
        if(estado){
            huesped = huespedData.BuscarHuespedPorId((int)jtHuespedes.getValueAt(i, 0));
            JOptionPane.showMessageDialog(null, huesped);
            jbCompletarReserva.setEnabled(estado);
        }else{
            JOptionPane.showMessageDialog(null, "El cliente esta vetado de por vida");
            jbCompletarReserva.setEnabled(estado);
        }
    }//GEN-LAST:event_jtHuespedesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCompletarReserva;
    private javax.swing.JComboBox<String> jcbFiltroHuesped;
    private javax.swing.JComboBox<String> jcbTipoHab;
    private com.toedter.calendar.JDateChooser jdcFechaIn;
    private com.toedter.calendar.JDateChooser jdcFechaOut;
    private javax.swing.JPanel jpContenedor1;
    private javax.swing.JPanel jpContenedor2;
    private javax.swing.JTable jtHabitaciones;
    private javax.swing.JTable jtHuespedes;
    private javax.swing.JTextField jtfBuscador;
    private javax.swing.JTextField jtfCantPers;
    private javax.swing.JTextField jtfCantPersRestantes;
    // End of variables declaration//GEN-END:variables

    private void armarTablaHuesped() {
        modeloHuesped.addColumn("ID");
        modeloHuesped.addColumn("Nombre");
        modeloHuesped.addColumn("DNI");
        modeloHuesped.addColumn("Correo");
        modeloHuesped.addColumn("Celular");
        modeloHuesped.addColumn("Domicilio");
        modeloHuesped.addColumn("Estado");
        jtHuespedes.setModel(modeloHuesped);
    }
    
    private void cargarTablaHuespedes() {
        for (Huesped huesped : listaHuespedes) {
            modeloHuesped.addRow(new Object[]{
                huesped.getIdHuesped(),
                huesped.getNombre(),
                huesped.getDni(),
                huesped.getCorreo(),
                huesped.getCelular(),
                huesped.getDomicilio(),
                huesped.isEstado()
            });
        }
    }
    
    private void borrarFilasHuespedes() {
        int f = jtHuespedes.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloHuesped.removeRow(f);
        }
    }
}
